# Generated by Django 2.2.6 on 2020-01-19 12:25

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='item_pics')),
                ('produc_color', models.CharField(max_length=100)),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('euro', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=70, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('catagory', models.CharField(choices=[('KOBIETA', 'Women'), ('MĘŻCZYZNA', 'Men'), ('DZIECKO', 'Kids')], default='KOBIETA', max_length=20)),
                ('variety', models.CharField(choices=[('RAMIĘ', 'Shoulder Bag'), ('ZAKUPY', 'Tote Bag'), ('PAS', 'Belt Bag'), ('PORTMONETKA', 'Purse'), ('PLECAK', 'Backpack'), ('PORTFEL', 'Wallet'), ('DZIECI', 'Kids Product')], max_length=20)),
                ('discription', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('whole_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('location', models.CharField(choices=[('IT', 'Italy'), ('FR', 'France'), ('CH', 'China')], default='IT', max_length=2)),
                ('color', models.ManyToManyField(to='vero_fasion.Color')),
            ],
        ),
    ]
